sass:
  style: compressed

#  Build settings
markdown: kramdown

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

#  Site settings
title: Community Capacity Building
description: Making positive community change possible
url: http://www.communitycapacity.co.uk
baseurl:
email: ccb@valonline.org.uk
phone: 0116 257 5050
github: richardatval/www.communitycapacity.co.uk
logo_path: /img/logo.svg
copyright: "Community Capacity Building is a project of Voluntary Action Leicester. Voluntary Action Leicester is a registered charity (No. 509300) Company Limited by Guarantee (No. 1357513) Registered in England and Wales."

#  Social media settings

facebook: "Community-Capacity-Building-Project-CCB-796315400483436"
twitter : ""
instagram: ""
permalink: none

# Services

analyticstracking: " "

# Pagination

paginate: 9
paginate_path: "/our-work/:num/"

#  Timezone
timezone: Europe/London

exclude: ['bower.json']

# Conditional Stylesheets

conditionalstylesheets:
  - target: "ie9"
    path: "/css/ie9.css"

#  Configuration for prose.io online editor
prose:
  ignore: 
    - '_includes'
    - 'assets'
    - '_assets'
    - '_layouts'
    - '_plugins'
    - '/.jekyll-metadata'
    - 'feed.xml'
    - 'js'
    - 'css'
    - '_sass'
  media: img
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "summary"
        field:
          label: "Summary"
          element: "textarea"
          value: null
      - name: "primary-image"
        field:
          label: "Primary Image"
          element: "text"
          placeholder: "/img/your-image.jpg"
          value: null
      - name: "layout"
        field:
          label: "Layout"
          element: "select"
          value: "default"
          options:
            - name: 'Default'
              value: 'default'
            - name: 'No Sidebars'
              value: 'no-sidebars'
      - name: "category"
        field:
          label: "Category"
          element: "select"
          value: "default"
          options:
            - name: 'Coalville & Greenhill'
              value: 'coalville-greenhill'
            - name: 'Loughborough'
              value: 'loughborough'
            - name: 'Measham'
              value: 'measham'
            - name: 'Wigston'
              value: 'wigston'