  # This file contains details of people in the organisation.
  #
  # Options:
  # - name: "name of the person"
  #   img: "path to picture of person relative baseurl"
  #   role: "role of person within organisation"
  #   phone: "telephone number"
  #   email: "email address of person"
  #   website: "personal website of person"
  #   bio: "a paragraph of text explaining the persons background"
  - name: "Ilir Demaj"
    img: "/img/profiles/ilir-demaj.jpg"
    email: "ilir.d@valonline.org.uk"
    bio: |+
        Ilir started working for VAL in 2009 as a Volunteer Advisor for Charnwood borough, soon becoming Development and Volunteer Advisor covering Charnwood and Melton boroughs. He worked in partnership with voluntary groups, charities, universities, colleges, the Job Centre, libraries and local councils to develop volunteering roles and provide volunteering advice to the general public.
        
        Since 2015, Ilir has been working on the Community Capacity Building (CCB) project as a Community Development Officer. He initially worked in Hastings ward in Loughborough and the villages of Bagworth and Thornton in Hinckley & Bosworth Borough, and has since expanded out to the Lemyngton ward in Loughborough and into Measham in North West Leicestershire.
        
        Ilir is an active volunteer in the community and has been a trustee with Shepshed Dolphins Swimming Group for the last 3 years.
  - name: "Dave Cliffe"
    img: "/img/profiles/dave-cliffe.jpg"
    email: "dave.c@valonline.org.uk"
    bio: |+
       Dave started working in VAL’s Policy Team in 2011 and later moved into the Volunteering Team as a Development and Volunteering Advisor. As part of this role Dave worked across Blaby District, Oadby & Wigston Borough, Harborough District and North West Leicestershire. This involved working in partnership with local community groups, charities, community services, colleges, libraries and local councils to develop new volunteering opportunities and to support the general public to start volunteering.
       
       Since 2015, Dave has been working on the CCB project as a Community Development Officer. Dave initially worked in the Greenhill and Agar Nook areas of Coalville and South Wigston, and has since expanded out to the rest of Coalville and into Wigston Magna.
       
       Outside of his work with VAL, Dave has volunteered with several local schools and colleges and helped to organise a number of local events.
